// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAVmUo8fRZEbGoSr3AKiB38o_1LMKf8L8I',
    appId: '1:185570730993:web:cd52bd7350b6857c62da50',
    messagingSenderId: '185570730993',
    projectId: 'quizgame-4213e',
    authDomain: 'quizgame-4213e.firebaseapp.com',
    storageBucket: 'quizgame-4213e.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDC5GdjK3Q517wcjgxHt9iFc616mQY35hU',
    appId: '1:185570730993:android:f90dcefac695328d62da50',
    messagingSenderId: '185570730993',
    projectId: 'quizgame-4213e',
    storageBucket: 'quizgame-4213e.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCICJFSAMKEqNp1G8vL7aELDZAF1dI0_IQ',
    appId: '1:185570730993:ios:870b62e6ad773ea162da50',
    messagingSenderId: '185570730993',
    projectId: 'quizgame-4213e',
    storageBucket: 'quizgame-4213e.firebasestorage.app',
    iosBundleId: 'com.example.quizGame',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCICJFSAMKEqNp1G8vL7aELDZAF1dI0_IQ',
    appId: '1:185570730993:ios:870b62e6ad773ea162da50',
    messagingSenderId: '185570730993',
    projectId: 'quizgame-4213e',
    storageBucket: 'quizgame-4213e.firebasestorage.app',
    iosBundleId: 'com.example.quizGame',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAVmUo8fRZEbGoSr3AKiB38o_1LMKf8L8I',
    appId: '1:185570730993:web:8d7a1e1aff3cacc262da50',
    messagingSenderId: '185570730993',
    projectId: 'quizgame-4213e',
    authDomain: 'quizgame-4213e.firebaseapp.com',
    storageBucket: 'quizgame-4213e.firebasestorage.app',
  );
}
